### ISSUE TITLE
How is this used? Usage link is forbidden. 

### ISSUE THREAD

**Issue by ojsglobal** [Cordobo/cordova-plugin-ios-camera-permissions#2]
Would you be able to provide a working link for correct usage?

Thanks.

**Comment by Cordobo** [comment]
@ojsglobal 
Do you need additional information apart from
http://cordobo.com/2269-cordova-plugin-for-nscamerausagedescription-in-ios-10/

**Comment by ojsglobal** [comment]
The link is 403 Forbidden.

**Comment by Cordobo** [comment]
If your public IP is something like 113.220 (China Telecom), you might experience problems

**Comment by ojsglobal** [comment]
I'm in the UK.

**Comment by Cordobo** [comment]
Try it again please. Looks like I blocked too many IP ranges
