### ISSUE TITLE
Video Capture Support?

### ISSUE THREAD

**Issue by leetpcuser** [Cordobo/cordova-plugin-ios-camera-permissions#3]
We implemented this and it works like a charm for the camera roll, and capturing a photo. However, the application still crashes when trying to capture a video.

**Comment by Cordobo** [comment]
The camera shouldn't be an issue here, the missing microphone permissions could be the reason.

Can you create a code sample you can share with me via plunkr/codepen/jsfiddle?

**Comment by Cordobo** [comment]
@leetpcuser I updated the plugin to support microphones. Please update and try again.

**Comment by leetpcuser** [comment]
I created a new Cordova plug in to handle the microphone and it worked.
