### ISSUE TITLE
How to customise the message?

### ISSUE THREAD

**Issue by mikl** [Cordobo/cordova-plugin-ios-camera-permissions#4]
I've been trying to customise the camera permission message? I've been trying a few things, for example this:

    <plugin name="cordova-plugin-ios-camera-permissions" spec="~1.0.4">
        <variable name="NSCameraUsageDescription" value="Custom camera message" />
        <variable name="NSPhotoLibraryUsageDescription" value="Custom photo gallery message" />
    </plugin>

But nothing seems to work. Can you point me in the right direction?

Also, the link to your website gives a 403 error, but it can be read on the WayBack Machine: https://web.archive.org/web/20161015002642/http://cordobo.com/2269-cordova-plugin-for-nscamerausagedescription-in-ios-10/

**Comment by Cordobo** [comment]
@mikl ,

at the time being, you need to manually change the string "This app needs photo library access" in plugin.xml itself:

`<config-file target="*-Info.plist" parent="NSPhotoLibraryUsageDescription">`
`<string>This app needs photo library access</string>`
`</config-file>`

Then do a
`$ cordova platform rm ios`
`$ cordova platform add ios`

in your shell/terminal.

I work on a version where you can configure it in cordovas config.xml.

**Comment by Cordobo** [comment]
@mikl regarding the 403 - can you tell me if your ip is in the range of 104.144.x.x or 39.87.x.x? Otherwise I need to talk to my hoster :)

**Comment by mikl** [comment]
@Cordobo ah, I see. Regarding the IP, no, I'm in the 85.195.x.x range. I do have IPv6 here, too, but since your domain doesn't have an AAAA record, that shouldn't matter.

**Comment by Cordobo** [comment]
@mikl Thanks for your reply regarding your IP. I close this question as "fixed".

**Comment by Cordobo** [comment]
For Reference, you can now customize the string on installation:

`cordova plugin add https://github.com/Cordobo/cordova-plugin-ios-camera-permissions.git --variable CAMERA_USAGE_DESCRIPTION="your usage message" --variable MICROPHONE_USAGE_DESCRIPTION="your microphone usage message here" --variable PHOTOLIBRARY_USAGE_DESCRIPTION="your photo library usage message here" --save`
