### ISSUE TITLE
Not setting messages from config.xml

### ISSUE THREAD

**Issue by apodolny** [Cordobo/cordova-plugin-ios-camera-permissions#6]
I've used the generator associated with the plugin and get the following in my config.xml
`    <plugin name="cordova-plugin-ios-camera-permissions" spec="~1.1.1">
        <variable name="CAMERA_USAGE_DESCRIPTION" value="Photo access required for uploading account photos and photos to chats." />
        <variable name="MICROPHONE_USAGE_DESCRIPTION" value="Microphone access required for uploading audio to chats." />
        <variable name="PHOTOLIBRARY_USAGE_DESCRIPTION" value="Photo access required for uploading account photos and photos to chats.." />
    </plugin>
</widget>`

but I'm still seeing the default messages in Xcode:
<img width="797" alt="screen shot 2017-03-31 at 4 45 34 pm" src="https://cloud.githubusercontent.com/assets/7158649/24572891/b51c5954-1631-11e7-99c4-48ea420b98c0.png">

**Comment by Cordobo** [comment]
@apodolny Thanks for your message.

For the changes in config.xml to take effect in your *.plist, run the following commands in your Terminal app
`cordova platform rm ios`
`cordova platform add ios`

**Comment by Cordobo** [comment]
Closing, if you still have experience problems please reopen this issue.
