### ISSUE TITLE
Add NSPhotoLibraryAddUsageDescription permission for iOS 11

### ISSUE THREAD

**Issue by amanvishnani** [Cordobo/cordova-plugin-ios-camera-permissions#7]
iOS 11 requires a new permission for NSPhotoLibraryAddUsageDescription to add new photos to photo library. Please add this permission to your plugin.

More details can be found [here](https://developer.apple.com/library/content/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html)

**Comment by Cordobo** [comment]
@amanvishnani Thanks for filing this issue

**Comment by Cordobo** [comment]
Release 1.2.0 with support for NSPhotoLibraryAddUsageDescription is online

**Comment by amanvishnani** [comment]
Thank You!
