### ISSUE TITLE
Usage link or examples?

### ISSUE THREAD

**Issue by jfred1979** [Cordobo/cordova-plugin-ios-camera-permissions#8]
I cannot access the page linked under usage (says forbidden). Could you add the usage instructions to the readme instead?

**Comment by Cordobo** [comment]
Hi @jfred1979 

the usage instructions provided are the same as here in the readme.

Did you struggle somewhere or need some additional help, which I could add to the readme?

**Comment by jfred1979** [comment]
I was not entirely clear about whether or not anything other than installation was necessary (for example, if any code was required in the Cordova project, if settings needed to be changed in the Cordova config, etc). However, it makes sense now and the readme does seem to cover its usage sufficiently.

**Comment by lougreenwood** [comment]
I just stumbled upon this plugin and I don't think the readme covers usage, for example:

* When is the permission requested? At app startup or when camera is accessed?
* If permission is rejected, how will the app handle subsequent requests to access the camera?
* Is this compatible with the html <file>, any adjustments needed?

**Comment by Cordobo** [comment]
As these are more general and platform-specific question, I update the Readme to link to the corresponding FAQs for iOS and Android
