### ISSUE TITLE
Not setting messages from config.xml

### ISSUE THREAD

**Issue by p3v9d5ui** [Cordobo/cordova-plugin-ios-camera-permissions#9]
Hi, I'm re-opening issue #6, because this is not working for me in verstion 1.2.0.

This is what I have in my config.xml:

`<plugin name="cordova-plugin-ios-camera-permissions" spec="^1.2.0">
        <variable name="CAMERA_USAGE_DESCRIPTION" value="Allow the app to use your camera to take photos of business cards" />
    </plugin>`

I've also run this:

`cordova platform rm ios
cordova platform add ios`

When I build in xcode, I don't get the message in the variable above. As in @apodolny 's screenshot in the other ticket, the default message in xCode is not updated.

**Comment by EstebanForge** [comment]
Can confirm too that this still happens.

Xcode 10.1

cordova-plugin-ios-camera-permissions v1.2.0

Have to update the info manually at Xcode before deploy.

**Comment by p3v9d5ui** [comment]
After looking into this more, this plugin doesn't seem to be very useful. Just remove the plugin and add this <edit-config> directive directly to your corodova config.xml file, in the ios platform, e.q.:

`<platform name="ios">
        <edit-config file="*-Info.plist" mode="overwrite" target="NSCameraUsageDescription">
            <string>Your message here...</string>
        </edit-config>
</platform>`
